#!/usr/bin/env python3

import i3ipc
import sys

i3 = i3ipc.Connection()
icon = ""


def printwincount(i3, e):
    l = i3.get_tree().leaves()

    print(icon + " " + str(len(l)) )
    sys.stdout.flush()


printwincount(i3, None)
i3.on('window::new', printwincount)
i3.on('window::close', printwincount)

i3.main()

#  
#  	
#  🪟
#  🗔
#  🗖
#  🗗
