#!/usr/bin/env python3

import i3ipc
import sys

i3 = i3ipc.Connection()

def printwintitle(i3, e):

    win = i3.get_tree().find_focused()

    if(not win.window or not win.window_title):
        print()
        sys.stdout.flush()
    else:
        msg = win.window_title
        max=70
        l=len(msg)

        if l > max:
            h = (max)//2
            sep="…"

            msg='{}{}{}'.format(msg[:h], sep, msg[l-h:])

        print("<span color='#555555'>"+msg+"</span>")
        sys.stdout.flush()



printwintitle(i3, None)
i3.on('window::new'     , printwintitle)
i3.on('window::close'   , printwintitle)
i3.on('window::title'   , printwintitle)
i3.on('window::focus'   , printwintitle)
i3.on('workspace::focus', printwintitle)

i3.main()

#  https://github.com/vivien/i3blocks/issues/190
#  https://i3ipc-python.readthedocs.io/en/latest/events.html
#  https://github.com/altdesktop/i3ipc-python
#  print("<span color='#3F3F3F'>"+msg+"</span>")

