#!/usr/bin/env python3

import i3ipc
import sys

i3 = i3ipc.Connection()

def printwincount(i3, e):

    l = i3.get_tree().find_focused().workspace().leaves()

    print(str(len(l)) + " ")
    sys.stdout.flush()

printwincount(i3, None)
i3.on('window::new', printwincount)
i3.on('window::close', printwincount)
i3.on('workspace::focus', printwincount)

i3.main()

#  https://github.com/vivien/i3blocks/issues/190
#  https://i3ipc-python.readthedocs.io/en/latest/events.html
#  https://github.com/altdesktop/i3ipc-python
